CandidateController update
CalculusEnjoyer/intellistart-java-2022-vanquishers pull request #102
Opened 2022-10-28 19:28 UTC by Archasmiel

2022-10-28 19:29 UTC, CalculusEnjoyer commented
|File|Coverage [43.86%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateSlotValidator.java)|95.45%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[BookingService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|75.44%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|54.39%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|28.75%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|9.18%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|8.74%|:x:|
|[BadResponseBuilder.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/52bde21584eb05e55bc5366d0e8cc4cfff77bb8b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fresponse%2FBadResponseBuilder.java)|0%|:x:|

|Total Project Coverage|46.97%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 19:36 UTC, CalculusEnjoyer requested changes

2022-10-28 19:36 UTC, CalculusEnjoyer commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +    } catch (InterviewApplicationException e) {
There is no need to catch InterviewApplicationException because when it is thrown in any place in the application, it is automatically picked by InterviewApplicationExceptionHandler, and Spring automatically makes an error response.

2022-10-28 19:36 UTC, CalculusEnjoyer commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CandidateController.java
> +    } catch (InterviewApplicationException e) {
As well as here

2022-10-28 20:10 UTC, CalculusEnjoyer commented on src/main/java/com/intellias/intellistart/interviewplanning/util/response/BadResponseBuilder.java
> +    return new ResponseEntity<>(jsonContent, status);
As well as there is no need for BadResponseBuilder because its logic already implemented in InterviewApplicationExceptionHandler

2022-10-29 06:27 UTC, VladOSIO2 commented on src/main/java/com/intellias/intellistart/interviewplanning/repositories/CandidateRepository.java
> +  Candidate findByFacebookId(@Param("facebookId") Long id);
Doesn't it work without the `@Query`? Spring JPA should map such methods automatically

2022-10-29 06:29 UTC, VladOSIO2 commented on src/main/java/com/intellias/intellistart/interviewplanning/services/BookingService.java
> +    ids.forEach(this::deleteBookingById);
Aren't this making N queries of deleting from DB instead of one?

2022-10-29 09:51 UTC, CalculusEnjoyer commented
|File|Coverage [46.84%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateSlotValidator.java)|95.45%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[BookingService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FBookingService.java)|75.44%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|54.39%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|28.75%|:green_apple:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.59%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/107cfd97eac19825e775ccf4abd4cdfa4ed60e01/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|9.18%|:x:|

|Total Project Coverage|47.46%|:green_apple:|
|:-|:-:|:-:|

2022-10-29 09:57 UTC, CalculusEnjoyer commented
|File|Coverage [43.85%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateSlotValidator.java)|95.45%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|54.39%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|28.75%|:green_apple:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|10.59%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/43e8fe021663bd19d81e2d92b5046866e98df4a5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|9.18%|:x:|

|Total Project Coverage|47.46%|:green_apple:|
|:-|:-:|:-:|

2022-10-31 08:41 UTC, CalculusEnjoyer commented
|File|Coverage [39.77%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateSlotValidator.java)|95.45%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|54.39%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|28.75%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|9.18%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/b435c10efd107dd111a5f5270bddf8efc80b5fb8/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|6.38%|:x:|

|Total Project Coverage|45.91%|:green_apple:|
|:-|:-:|:-:|

2022-10-31 12:39 UTC, CalculusEnjoyer commented
|File|Coverage [41.28%]|:green_apple:|
|:-|:-:|:-:|
|[CandidateSlotValidator.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Futil%2Fvalidation%2FCandidateSlotValidator.java)|95.45%|:green_apple:|
|[InterviewerService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|80.3%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|54.39%|:green_apple:|
|[UserService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|35.29%|:green_apple:|
|[CandidateService.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|28.75%|:green_apple:|
|[SecurityController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fauth%2FSecurityController.java)|9.18%|:x:|
|[CandidateController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/86d9ac5ddee5c55e85f2d53510ba65d84eb65946/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCandidateController.java)|7.56%|:x:|

|Total Project Coverage|46.51%|:green_apple:|
|:-|:-:|:-:|

2022-10-31 13:14 UTC, CalculusEnjoyer approved these changes

2022-11-01 17:52 UTC, merged