Implement createBooking method (/bookings) in CoordinatorController
CalculusEnjoyer/intellistart-java-2022-vanquishers pull request #98
Opened 2022-10-27 20:42 UTC by olexandra-shokotko

2022-10-27 20:43 UTC, CalculusEnjoyer commented
|File|Coverage [47.03%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|50.65%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|46.49%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|42.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/88d180fe9ac5ba096ed8fcbbab2c2b139090eaa4/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|38.16%|:green_apple:|

|Total Project Coverage|31.72%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 07:47 UTC, CalculusEnjoyer commented
|File|Coverage [48.4%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|58.44%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|46.49%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|42.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/af77c5443429868b05681f143d04d51840c6af24/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|38.16%|:green_apple:|

|Total Project Coverage|32.09%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 08:56 UTC, CalculusEnjoyer commented
|File|Coverage [44.81%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|58.44%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|46.49%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|42.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|38.16%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/28e76f12dcdf1492567a73a978c553b5b34cf0f9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|15.09%|:green_apple:|

|Total Project Coverage|32.09%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 09:09 UTC, CalculusEnjoyer commented
|File|Coverage [41.21%]|:green_apple:|
|:-|:-:|:-:|
|[SecurityConfig.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fconfig%2FSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|58.44%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|46.49%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|42.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.95%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/727a3ae6ed5ab2dc74cc51208fb53661026b9c77/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|15.09%|:green_apple:|

|Total Project Coverage|34.32%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 09:15 UTC, VladOSIO2 commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CoordinatorController.java
> +  public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto) {
As discussed in team chat, it would be better to return DTO in ResponseEntity. This will also resolve the error of recursively JSONifying the object by removing the need to JSONify the model at all, so no need `@JSONIgnore` annotations in data models

2022-10-28 09:16 UTC, CalculusEnjoyer requested changes

2022-10-28 09:16 UTC, CalculusEnjoyer commented on src/main/java/com/intellias/intellistart/interviewplanning/config/SecurityConfig.java
> +    http.cors().and().csrf().disable();
Everything looks OK, but we agreed that configs for testing should be stored locally until we set up OAuth2, so maybe it is better to remove that line.

2022-10-28 09:26 UTC, CalculusEnjoyer commented
|File|Coverage [39.89%]|:green_apple:|
|:-|:-:|:-:|
|[InterviewPlanningApplication.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|73.68%|:green_apple:|
|[Booking.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|58.44%|:green_apple:|
|[CandidateSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateSlot.java)|46.49%|:green_apple:|
|[InterviewerSlot.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerSlot.java)|42.14%|:green_apple:|
|[CoordinatorController.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FCoordinatorController.java)|25.95%|:green_apple:|
|[Interviewer.java](https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/blob/0e7867e4e4773f671c01ea9b5b565eff8e5df7b5/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewer.java)|15.09%|:green_apple:|

|Total Project Coverage|34.05%|:green_apple:|
|:-|:-:|:-:|

2022-10-28 09:28 UTC, olexandra-shokotko commented on src/main/java/com/intellias/intellistart/interviewplanning/config/SecurityConfig.java
> +    http.cors().and().csrf().disable();
Agree. I fixed it

2022-10-28 09:29 UTC, olexandra-shokotko commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CoordinatorController.java
> +  public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto) {
Maybe it is last commit. It was fixed in one of the next commits

2022-10-28 09:45 UTC, VladOSIO2 commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CoordinatorController.java
> +  public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto) {
Oh, really, my bad. Good then, just a little question - is `@JsonIgnore` still needed in Interviewer class?

2022-10-28 09:58 UTC, CalculusEnjoyer approved these changes
All is OK

2022-10-28 10:05 UTC, olexandra-shokotko commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CoordinatorController.java
> +  public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto) {
Yes. For method getAllInterviewers in CoordinatorController. It returns the list of interviewers. And Interviewer entity has set with slots. It causes JSON recursive in response. And as I understand I cant return list of InterviewerDTO in method getAllInterviewers.

2022-10-28 10:13 UTC, VladOSIO2 commented on src/main/java/com/intellias/intellistart/interviewplanning/controllers/CoordinatorController.java
> +  public ResponseEntity<Booking> createBooking(@RequestBody BookingDto bookingDto) {
Understood. Good then

2022-10-28 10:13 UTC, VladOSIO2 approved these changes
Good

2022-10-28 10:43 UTC, merged